exports.appName = 'HousoRento'

exports.actions = {
    FETCH_PROPERTY: 'FETCH_PROPERTY',
    FETCH_PROPERTIES: 'FETCH_PROPERTIES',
    FETCH_USER_DATA: 'FETCH_USER_DATA',
    FETCH_OTHER_USER_DATA: 'FETCH_OTHER_USER_DATA',
    CLEAR_USER_DATA: 'CLEAR_USER_DATA',
}